Add camera lag note
freemocap/freemocap pull request #360
Opened 2023-04-04 18:51 UTC by philipqueen

Adds a note in the camera controller groupbox that says "NOTE: Use fewer cameras or decrease resolution if you are experiencing lag"

<img width="860" alt="Screen Shot 2023-04-04 at 12 50 28 PM" src="https://user-images.githubusercontent.com/24758117/229891269-7cf8c1dc-2163-402a-b25f-fe1d598dd85d.png">

2023-04-04 18:58 UTC, jonmatthis requested changes

2023-04-04 18:58 UTC, jonmatthis commented on freemocap/gui/qt/widgets/camera_controller_group_box.py
> +        lag_note_label = QLabel("NOTE: Use fewer cameras or decrease resolution if you are experiencing lag")
```suggestion
        lag_note_label = QLabel("NOTE: If you experience frame lag, decrease the resolution or use fewer cameras. We are working on a fix for this")
```

2023-04-04 19:00 UTC, jonmatthis commented
> Adds a note in the camera controller groupbox that says "NOTE: Use fewer cameras or decrease resolution if you are experiencing lag"
> 
> <img alt="Screen Shot 2023-04-04 at 12 50 28 PM" width="860" src="https://user-images.githubusercontent.com/24758117/229891269-7cf8c1dc-2163-402a-b25f-fe1d598dd85d.png">

Is that really what your Charuco square size text box looks like? 

Can you tweak the CSS file again to make that readable? Also change the color that "white on teal" parts of the parameter trees, etc. to be higher contrast (probably by making that text darker)

2023-04-04 19:05 UTC, philipqueen commented
Yes, if I'm in darkmode it still overrides the text boxes to black. I can look into that and the color contrast thing as a different pull request.

2023-04-05 14:42 UTC, jonmatthis commented
Oh wait... did you duplicate some of this work in the other PR?

if so, either remove the duplicate work from that PR and keep it all in this one, or close this PR and integrate the work into the other one.

2023-04-05 15:27 UTC, philipqueen commented
Closing this PR because I made the color branch off of this instead of main

2023-04-05 15:27 UTC, closed without merging