Color contrast improvements
freemocap/freemocap pull request #361
Opened 2023-04-04 21:42 UTC by philipqueen

This pull request solves a number of the major color contrast issues in the GUI, although not all of them.

First, it fixes the major mac darkmode problem by setting a white background on all of the QLineEdit objects, turning this: 
<img width="860" alt="Screen Shot 2023-04-04 at 12 50 28 PM" src="https://user-images.githubusercontent.com/24758117/229927428-15d31afa-795b-4219-806d-d0abbfb9120f.png">
into this:
<img width="855" alt="Screen Shot 2023-04-04 at 3 32 10 PM" src="https://user-images.githubusercontent.com/24758117/229927474-993d5b0d-900c-474e-9801-5906d39bf3ca.png">

Second, it increases the color contrast of certain text, like the parameter tree text is now dark instead of white:
<img width="467" alt="Screen Shot 2023-04-04 at 3 33 54 PM" src="https://user-images.githubusercontent.com/24758117/229927760-3d394624-f61e-4fc6-a9ae-294ffb57d0b1.png">
And the text for the link to the privacy policy is now dark instead of white:
<img width="504" alt="Screen Shot 2023-04-04 at 3 34 29 PM" src="https://user-images.githubusercontent.com/24758117/229927878-adb3979c-2773-47a4-b6b9-5ec83ede84a0.png">

The only remaining issues are the user selections in the parameter tree that are still displaying dark on a mac in darkmode. They are only dark when they are selected (you can see them just fine when not selected). I can't figure out how to fix them in the css. Examples of what I'm talking about:

<img width="488" alt="Screen Shot 2023-04-04 at 3 03 46 PM" src="https://user-images.githubusercontent.com/24758117/229929035-aad464e8-464f-448b-9929-2a4e0b31ed79.png">
<img width="438" alt="Screen Shot 2023-04-04 at 3 03 58 PM" src="https://user-images.githubusercontent.com/24758117/229929048-bed3891e-7c7a-4f79-b400-c60beb383ab0.png">

2023-04-05 14:40 UTC, jonmatthis requested changes
we gotta fix that "black text on black bkgrd" thing before we merge - we can pair on it

2023-04-05 14:40 UTC, jonmatthis commented on freemocap/gui/qt/widgets/camera_controller_group_box.py
> +        lag_note_label = QLabel("NOTE: Use fewer cameras or decrease resolution if you are experiencing lag")
```suggestion
        lag_note_label = QLabel("NOTE: If you experience lag in your camera views, decrease the resolution and/or use fewer cameras.\nWe are working on a fix which should be done 'soon' (written: 2023-04-05)")
```

Changed my mind again on this text, please make sure that newline `\n` works properly in the GUI

2023-04-05 15:38 UTC, philipqueen commented
The new line renders properly in the note text. It might look nicer if we center it but thats ok

![Screen Shot 2023-04-05 at 9 36 34 AM](https://user-images.githubusercontent.com/24758117/230131759-cdaccd40-59db-43df-9911-d140e761d9a0.png)

2023-04-05 18:27 UTC, philipqueen commented
@jonmatthis This is all ready except for some lingering black on black inside the parameter trees (for processing and camera settings). I've had no luck fixing it myself, if you'd like to pair on it.

2023-04-07 15:06 UTC, jonmatthis approved these changes

2023-04-07 15:08 UTC, merged